#!/usr/bin/env python3


import pytest
import tempfile
from io import StringIO
from collections import namedtuple
from seqtools.plot_al_conservation import *
logger.setLevel(logging.DEBUG)

plt.switch_backend('TkAgg')


NEWICK = '((ENSPCOG:37.7826,ENSMICG:37.7826):36.0542,(((ENSSBOG:16.0705,ENSCCAG:16.0705):3.61059,ENSANAG:19.6811,ENSCJAG:19.6811):23.4702,((ENSCANG:19.4223,(ENSCSAG:13.7496,(ENSPANG:12.4,ENSCATG:12.4,(ENSMMUG:5.27817,ENSMNEG:5.27816,ENSMFAG:5.27817):7.12184,ENSMLEG:12.4):1.34957):5.67273):10.0192,(ENSNLEG:20.1892,(ENSPPYG:15.7622,((ENSG000:6.6509,(ENSPTRG:2.82006,ENSPPAG:2.82006):3.83085):2.41219,ENSGGOG:9.0631):6.69907):4.42705):9.25233):13.7097):30.6856);'

FASTA = """>ENSPCOG
AAGGCGCGCGGCGGGGTTCAAGCTGTCGTGCATGAGAAGCAACATCCCCAGGAGCCACTCGAAGATGTCCAGCACGCTATCGTGCTCGGACCTCGAGATTCGCTTCTGAATCCTGTCAACGCCTCCTATACTGCGCGTGCGGGCTATTGGATTGGTATT------------------GTCGACCTGACATTCGAGCAATGCGTGTTGCAATGGAACTTGGCCCTCCAGCCACCGCACAAG------------------------ACTGCAAGTCAGGAGGTGAGACGTACACGAAACGATTTCACGCAGATGGTCCACAGTCAC---CTACACGAG
>ENSMICG
CGGCCACGTGGCGTGGTCCAAGCCGTCGTACATCAGAAGCAACATCCCCACGAGCCTCTTGAGGACGTGCAGCATGCTACTGTGCTCGGC---------------CTGTATCCTGTCAACGCCTGCCATACTGCTCGTGCGGGTCATTGGATTAGCATC------------------GTCGATCTGACATTCGCGCAATGCGTGTTACAATGGAACTTGGTTCATCAACCACCGCTCAAGGGCGTGACCCGGTACTATGGGAGAACTGCAAGTCAGGAGGTGAGACGTACGCGGAATGATGTCACGCAGATGGTCCACAGGCAC---CTACATGAG
>ENSSBOG
GAGTCACACGGTAGGGCTCAAGCCGTCGAACATCAGAAGCAACATCCCCAGGAGCCCCTTGAGGACGTCCAGCACGCAACCGTGCTCGGC---------------TTGGCACCTGTCAATGCGCACCATACTGCTCGTGCGGGCTATTGGATAGGTATT------------------GTCGATCTGACATTCAAGCGATGCGTATTACAATGGAATTTAGTCCGGCAGCCACCGCCCAAGGGGGTGACACGGTACTATGGAAGGACCGCCAGTCAGGAGGTGAGACGCACCCGAAACGATTTCACACAGATGCTTCACAGGCAC---CTACATGAG
>ENSCCAG
GAGTCACACGGCAGGGCTCAAGCTGTCGTACATCAGAAGCAACATCCCCAGGAGCCCCTTGAGGACGTTCAGCACGCTACCGTGCTCGGC---------------TTGGTACCTGTCAATGCCAACCATACTGCTCGTGCGGGCTGTTGGATAGGTATT------------------GTCGATCTGACATTCAAGCGATGTGTGTTACAATGGAATTTGGTCCAGCAGCCACCGTCCAAAGGGGTGACACGGTACTATGGAAGGACCGCCAGTCAGGAGGTGAGGCGCACCCGAAACGATCTCACACAGATGCTTCACAGGCAC---CTACATGCG
>ENSANAG
GAATCACACGGCAGGGCACAAACTGTCGTACATCAGAAGCAACATCCCCAGGAGCCCCTTGAGGACGTCCAGCACGCGACCGTGCTCGGC---------------TTGGCACCTGTCATTGCCTACCATACTGCTCGTGCGGGTTATTGGATAGGTATTGAAAACCAAATTAAGTGTGTCGATCTGACATTTAAGCGATGCGTGTTACAATGGAATTTGGTCCAGCAGCCACCGCCCAAGGGGGTGACACGGTACTATGGAAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCTTCACAGGCAC---CTACATGAG
>ENSCJAG
AAGTCACACGGTAGGGCTCAGGCTGTCGTAGATCAGAAGCAACATCCCCAGGAGCCCCTTGAGGACGTCCAGCACGCCACCGTGCTCGGC---------------TTGGCACCTGTCCATGCTTACCATACTGCTCGTGCGGGCTATTGGATAGGTATT------------------GTCGATTTGACATTCAAGCAATGCGTGTTACAATGGAATTTGGTCTACCAGCCACCGCCCAAGGGGGTGACACGGTACTATGGAAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCTTCACAGGCAC---CTACATGTC
>ENSCANG
GAATCACACGGCGGGGCCCAAACTGTTGAACTTCGGAAACAACATCCTACGGAGCCC------GACGTCCAACACGCTACCGTACTCGGC---------------CTGGTGCCTGTCGACGTTTACCATACTGCTCGTGCGGGCTATTGGATTGATATC------------------GTCTACCTTGCATTCGAGCAATGCGTCCTACAATGGAACTTGATCGTCCAGCCACCGCACAAGAGGGTGACACGGTACTACGGGAGGACCGCGAGCCAGGAGGTGAGACGCACGCGAAATGATTTGACACAGATGCTCCACAAGCAC---CTACATGAA
>ENSCSAG
GATTCACACGGCGGGGCACAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTCGAGGATGTCCAGCACGCTACCGTGCTCGGC---------------CTGAAACCTGTTAACGTCTACCATACTGCTCGTGCGGGCTATTGGATCGATATT------------------GTTGACTTGGCATTCAGCCGATGCGTGTTACAATGGAATTTGGTCCGCCAGCCGCCGCCCAAGGGGGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCCTCACGAGCAT---CTACATGGA
>ENSPANG
GAGTCGCACGGCGGGGCTCAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTTGAAGATGTACAGCACGCTAACGTGCTCGGC---------------CTGGAACCTGTTAACGTCTACCATACTGCTCGTGCGGGCTATTGGATCGATATC------------------GTGGACTTGGCATTCAGGCGATGCGTGTTACAATGGAATTTGGTCCACCAGCCGCCGCCCAAGGGCGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACTCGAAATGATTTCACACAGATGCCTCACGAGCAC---CTGCATGAA
>ENSCATG
GAGTCACACGGCGGGGCTCAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTTGAGGACGTCCAGCACGCTACCGTGCTCGGC---------------CTGGAACCCGTTAACGTCTACCATACTGCTCGTGCGGGCTATTGGATCGATATC------------------GTGGACTTGGCATTCAAGCGATGCGTGTTACAATGGAATTTGGTCTACCAGCCGCCGCCCAAGGGGGTGACACGGTACTATGGG---ACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCCTCACGAGCAC---CTACATGAA
>ENSMMUG
GAGTCACACGGCGGGGCTCAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTTGAAGATGTCCAGCACGCTACCGTGCTCGGC---------------CTGGAACCTGTTAACGTCTACCATACTGCTCGTGCGGGTTATTGGATCGATATC------------------GTGGACTTGGCATTCAGGCGATGCGTGTTACAATGGAATTTGGTCTACCAGCCGCCGCCCAAGGGCGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCCTCACGAGCAC---CTACATGAA
>ENSMNEG
GAGTCACACGGCGGGGCTCAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTTGAGGATGTCCAGCACGCTACCGTGCTCGGC---------------CTGGAACCTGTTAACGTCTACCATACTGCTCGTGCGGGTTACTGGATCGATATC------------------GTGGACTTGGCATTCAGGCGATGCGTGTTACAATGGAATTTGGTCTGCCAGCCGCCGCCCAAGGGGGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCCTCACGAGCACAACCTACATGAA
>ENSMFAG
GAGTCACACGGCGGGGCTCAAACTGTCGTACATCAGAAGCAACATCCCAAGGAGCCCCTTGAGGATGTCCAGCACGCTACCGTGCTCGGC---------------CTGGAACCTGTTAACGTTTACCATACTGCTCGTGCGGGTTATTGGATCGATATC------------------GTGGACTTGGCATTCAGGCGATGCGTGTTACAATGGAATTTGGTCTACCAGCCGCCGCCCAAGGGGGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAACGATTTCACACAGATGCCTCACGAGCAC---CTACATGAA
>ENSMLEG
GAGTCACACGGCGTGGCTCAAACTGTCGTACAT------CAACATCCCAAGGAGCCCCTTGAGAATGTCCAGCACGCTACCGTGCTCGGT---------------CTGGAACCTGTTCGCGTCTACCATACTGCTCGTGCGGGCTATTGGATCGACATC------------------GTGGATTTGGCATTCAGGCGATGCGTGCTACAATGGAATTTGGTCTACCAACCGCCGCCCAAGGGGGTGACACGGTACTATGGGAGGACCGCAAGTCAGGAGGTGAGACGTACGCGAAACGATTTCACACAGATGCCTCACGAGCAC---CTACATGAA
>ENSNLEG
GAGTCACACGGCGAAGCCCAGACTGTCGTACATCAGAAGCAACACCCCAAGGAGCCCCTTGAGGACGTACAGCACGCTACCGTGCTCGGG---------------CTGGCACCTGTTGACGTCTACCATACTGCTCGTGCGGGCTATTCGATTACCATC------------------GTCGACCTGGCATTCGAGCGATGCGTGTTACAATGGAATGTGGTTCGACAGCCACCGCCCAAGGGGGTGACACGGTACTATGGGAGGACCGCGAGTCAAGAGGTAAGACGAACGCGAAATGATTTCACCCAGATGCTTCACAAGCAT---CTGCATGAA
>ENSPPYG
GAGTCACACGGCGGGGATCAAACTGTGGCACATCGGAAGCAACATCCCAAGGAGCCCCTTGAGGACGTCCAGCACGCTACTGTACTCGGC---------------CTGGCACCCGTT------TACCATACTGCTCGTGCAGGCTATTCGATTGATATC------------------GTCGACCTGGCATTCGAACGATGCGTGTTACAATGGAACGTGGTCCACCAGCCACCACCTAAGGGGGTGACACGGTATTATGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAATGATTTCACACAGATGCTTCACAAGCAC---CTACATGAA
>ENSG000
GAGTCACACGGAGGGGATCAAACTGTGGTACAGCGGAAGCAACATCCCAAGGAGCCCCTTGAGGACGTCCAGCACGCCACTGTGCTCGGC---------------CTGGCACCTGTT------TACCATACTGCTCGGGCAGGCTATTCGATTGAGATC------------------GTCGACCTAGCATTCGAGCCATGCGTGTTACAATGGAACGTGGTCCAACAGCCACCACCCAAGGGGGTGACACGGTACTACGGGAGGACCGCAAGCCAGGAAGTGAGACGCACGCGAAATGATTTTACACAGATGCTTCATAAGCAT---CTGCATGAG
>ENSPTRG
GAGTCACACGGAGGGGATCAAATTGTGGTACAGCGGAAGCAACATCCCAAGGAGCCCCTTGAGGACGTCCAGCACGCTACTGTGCTCGGC---------------CTGGCACCTGTT------TACCATACTGCTCGTGCGGGCTATTCGATTGAGATC------------------GTCGACCTAGCATTCGAGCCATGCGTGTTACAGTGGAACGTGGTCCAACAGCCACCACCCAAGGGGGTGACACGGTACTACGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAATGATTTCACACAGATGCTTCATAAGCAT---CTGCATGAG
>ENSPPAG
GAGTCACACGGAGGGGATCAGATTGTGGTACAGCGGAAGCAACATCCCGAGGAGCCCCTTGAGGACGTCCAGCACGCTACTGTGCTCGGC---------------CTGGCACCTGTT------TACCATACTGCTCGTGCGGGCTATTCGATTGGGATC------------------GTCGACCTAGCATTCGAGCCATGCGTGTTACAGTGGAACGTGACCCAACAGCCACCACCCAAGGGGGTGACACGGTACTACGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAATGATTTCACACAGATGCTTCATAAGCAT---CTGCATGAG
>ENSGGOG
GAGTCACACGGAGGGGATCAAACTGTGGTACAGCGGAAGCAACATCCCAAGGAGCCCCTTGAGGACGTCCAGCACGCTACTGTGCTTGGC---------------CTGGCACCTGTT------TACCATACTGCTCGTGCAGGCTATTCGATTGAGATC------------------GTCGACCTGGCATTCGAGCCATGCGTGTTACAGTGGAACGTGGTCCAACAGCCACCACCCAAGGGGGTGACGCGGTACTACGGGAGGACCGCAAGTCAGGAGGTGAGACGCACGCGAAATGATTTCACACAGATGCTTCATAAGCAT---TTGCATGAG
"""

FASTA_AA = """>ENSPCOG
KARGGVQAVVHEKQHPQEPLEDVQHAIVLGPRDSLLNPVNASYTARAGYWIGI------VDLTFEQCVLQWNLALQPPHK--------TASQEVRRTRNDFTQMVHSH-LHE
>ENSMICG
RPRGVVQAVVHQKQHPHEPLEDVQHATVLG-----LYPVNACHTARAGHWISI------VDLTFAQCVLQWNLVHQPPLKGVTRYYGRTASQEVRRTRNDVTQMVHRH-LHE
>ENSSBOG
ESHGRAQAVEHQKQHPQEPLEDVQHATVLG-----LAPVNAHHTARAGYWIGI------VDLTFKRCVLQWNLVRQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHRH-LHE
>ENSCCAG
ESHGRAQAVVHQKQHPQEPLEDVQHATVLG-----LVPVNANHTARAGCWIGI------VDLTFKRCVLQWNLVQQPPSKGVTRYYGRTASQEVRRTRNDLTQMLHRH-LHA
>ENSANAG
ESHGRAQTVVHQKQHPQEPLEDVQHATVLG-----LAPVIAYHTARAGYWIGIENQIKCVDLTFKRCVLQWNLVQQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHRH-LHE
>ENSCJAG
KSHGRAQAVVDQKQHPQEPLEDVQHATVLG-----LAPVHAYHTARAGYWIGI------VDLTFKQCVLQWNLVYQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHRH-LHV
>ENSCANG
ESHGGAQTVELRKQHPTEP--DVQHATVLG-----LVPVDVYHTARAGYWIDI------VYLAFEQCVLQWNLIVQPPHKRVTRYYGRTASQEVRRTRNDLTQMLHKH-LHE
>ENSCSAG
DSHGGAQTVVHQKQHPKEPLEDVQHATVLG-----LKPVNVYHTARAGYWIDI------VDLAFSRCVLQWNLVRQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEH-LHG
>ENSPANG
ESHGGAQTVVHQKQHPKEPLEDVQHANVLG-----LEPVNVYHTARAGYWIDI------VDLAFRRCVLQWNLVHQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEH-LHE
>ENSCATG
ESHGGAQTVVHQKQHPKEPLEDVQHATVLG-----LEPVNVYHTARAGYWIDI------VDLAFKRCVLQWNLVYQPPPKGVTRYYG-TASQEVRRTRNDFTQMPHEH-LHE
>ENSMMUG
ESHGGAQTVVHQKQHPKEPLEDVQHATVLG-----LEPVNVYHTARAGYWIDI------VDLAFRRCVLQWNLVYQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEH-LHE
>ENSMNEG
ESHGGAQTVVHQKQHPKEPLEDVQHATVLG-----LEPVNVYHTARAGYWIDI------VDLAFRRCVLQWNLVCQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEHNLHE
>ENSMFAG
ESHGGAQTVVHQKQHPKEPLEDVQHATVLG-----LEPVNVYHTARAGYWIDI------VDLAFRRCVLQWNLVYQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEH-LHE
>ENSMLEG
ESHGVAQTVVH--QHPKEPLENVQHATVLG-----LEPVRVYHTARAGYWIDI------VDLAFRRCVLQWNLVYQPPPKGVTRYYGRTASQEVRRTRNDFTQMPHEH-LHE
>ENSNLEG
ESHGEAQTVVHQKQHPKEPLEDVQHATVLG-----LAPVDVYHTARAGYSITI------VDLAFERCVLQWNVVRQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
>ENSPPYG
ESHGGDQTVAHRKQHPKEPLEDVQHATVLG-----LAPV--YHTARAGYSIDI------VDLAFERCVLQWNVVHQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
>ENSG000
ESHGGDQTVVQRKQHPKEPLEDVQHATVLG-----LAPV--YHTARAGYSIEI------VDLAFEPCVLQWNVVQQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
>ENSPTRG
ESHGGDQIVVQRKQHPKEPLEDVQHATVLG-----LAPV--YHTARAGYSIEI------VDLAFEPCVLQWNVVQQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
>ENSPPAG
ESHGGDQIVVQRKQHPEEPLEDVQHATVLG-----LAPV--YHTARAGYSIGI------VDLAFEPCVLQWNVTQQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
>ENSGGOG
ESHGGDQTVVQRKQHPKEPLEDVQHATVLG-----LAPV--YHTARAGYSIEI------VDLAFEPCVLQWNVVQQPPPKGVTRYYGRTASQEVRRTRNDFTQMLHKH-LHE
"""

FASTAS = {'nucl': FASTA, 'codon': FASTA, 'aa': FASTA_AA}


def plotal_setopts(altype='nucl', allow_N=False, ungap=True, records=None, recordsfile=None, treefile=None, slice=None,
         topology_only=False, compare_parts=None, compare_only=False, plotlist=None, colorscheme='default'):
    return (altype,allow_N,ungap,records,recordsfile,treefile,slice,topology_only,compare_parts,compare_only,plotlist,colorscheme)


optnames = ','.join(plotal_setopts.__code__.co_varnames)


OPTION_IDS, OPTIONS = tuple(zip(*[
    ('only_al_nucl',  plotal_setopts('nucl', plotlist='al')),
    ('only_al_nucl+allow_N',  plotal_setopts('nucl', plotlist='al', allow_N=True)),
    ('only_al_aa',    plotal_setopts('aa', plotlist='al')),
    ('only_al_codon', plotal_setopts('codon', plotlist='al')),
    ('al_aa,entropy',            plotal_setopts('aa', plotlist='al,entropy')),
    ('al_aa,entropy+allow_N',    plotal_setopts('aa', plotlist='al,entropy', allow_N=True)),
    ('al_aa,entropy,sp+allow_N', plotal_setopts('aa', plotlist='al,entropy,sp', allow_N=True)),
    ('tree,al',  plotal_setopts(plotlist='tree,al', treefile=StringIO(NEWICK))),
    ('al,tree',  plotal_setopts(plotlist='al,tree', treefile=StringIO(NEWICK))),
    ('al,gap,tree',        plotal_setopts(plotlist='al,gap,tree', treefile=StringIO(NEWICK))),
    ('al_aa,gap,tree',     plotal_setopts('aa', plotlist='al,gap,tree', treefile=StringIO(NEWICK))),
    ('al_codon,gap,tree',  plotal_setopts('codon', plotlist='al,gap,tree', treefile=StringIO(NEWICK))),
    ('al,gap,tree+clustalx',            plotal_setopts(plotlist='al,gap,tree', treefile=StringIO(NEWICK), colorscheme='clustalx')),
    ('al_aa,gap,tree+norecoding',       plotal_setopts('aa', plotlist='al,gap,tree', treefile=StringIO(NEWICK), colorscheme='Dark2')),
    ('al_aa,gap,tree+recodingclustalx', plotal_setopts('aa', plotlist='al,gap,tree', treefile=StringIO(NEWICK), colorscheme='Dark2/clustalx')),
    ('al_aa,gap,tree+clustalxtab10',    plotal_setopts('aa', plotlist='al,gap,tree', treefile=StringIO(NEWICK), colorscheme='clustalxtab20')),
    ('al,gap,pars,tree',    plotal_setopts(plotlist='al,gap,pars,tree', treefile=StringIO(NEWICK))),
    ('al,gap,pars+records', plotal_setopts(plotlist='al,gap', records='19,0,1')),
    #('al,gap,pars+recordsfile', plotal_setopts('nucl', plotlist='al,gap,pars', recordsfile=StringIO('ENSGGOG\nENSPCOG\nENSMICG\n')),
    #('al,gap,pars,tree+records', plotal_setopts(plotlist='al,gap,pars,tree', treefile=StringIO(NEWICK), records='19,0,1')), # NotImplemented
    ('al,gap+records+slice', plotal_setopts(plotlist='al,gap', records='19,0,1', slice='5:100')),
    ('only_al_compare_parts',      plotal_setopts(plotlist='al', compare_parts='(0:14);(14:)')),
    ('compare_parts',              plotal_setopts(compare_parts='(0:14);(14:)')),
    ('compare_parts+compare_only', plotal_setopts(compare_parts='(0:14);(14:)', compare_only=True)),
    ('compare_parts_implicit',     plotal_setopts(compare_parts='(14:)')),
    ('compare_parts_regex',        plotal_setopts(compare_parts='(NLE|PPY|G000|PTR|PPA|GGO)'))
    ]))

class Test_plot_al_conservation:
    @pytest.mark.parametrize(optnames, OPTIONS, ids=OPTION_IDS)
    def test_run(self, altype, allow_N, ungap, records, recordsfile, treefile, slice, topology_only,
                 compare_parts, compare_only, plotlist, colorscheme):
        plot_al_conservation(StringIO(FASTAS[altype]), 'fasta',
                             altype, allow_N, ungap, records, recordsfile, treefile, slice, topology_only,
                             compare_parts, compare_only, plotlist, colorscheme=colorscheme).display()
